# Generated by Django 5.2.4 on 2025-07-21 15:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("role", models.CharField(max_length=20)),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="folders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="LibraryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("url", models.URLField(max_length=2048)),
                ("query", models.TextField(blank=True)),
                ("source_type", models.CharField(default="Website", max_length=100)),
                ("added_timestamp", models.DateTimeField(auto_now_add=True)),
                ("summary", models.TextField(blank=True)),
                ("annotation", models.TextField(blank=True)),
                ("content_snippet", models.TextField(blank=True)),
                ("authors", models.CharField(blank=True, max_length=512)),
                ("year", models.CharField(blank=True, max_length=10)),
                ("pdf_url", models.URLField(blank=True, max_length=2048, null=True)),
                (
                    "main_pub_url",
                    models.URLField(blank=True, max_length=2048, null=True),
                ),
                ("doi", models.CharField(blank=True, max_length=255)),
                ("journal_name", models.CharField(blank=True, max_length=255)),
                ("volume", models.CharField(blank=True, max_length=50)),
                ("pages", models.CharField(blank=True, max_length=50)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("issn", models.CharField(blank=True, max_length=255)),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="research_assistant.folder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-added_timestamp"],
                "unique_together": {("user", "url")},
            },
        ),
    ]
